version: 2.1
orbs:
  node: circleci/node@5.1.0
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run test
  echo-sentence:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          name: Echo Mohammad
          command: echo "Hello Mohammad"
workflows:
  version: 2
  echo-after-build:
    jobs:
      - build-and-test
      - echo-sentence:
          requires:
            - build-and-test
